# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml
- .github/

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
# - jekyll-katex
# - jekyll-scholar

# Site settings
url: 'https://henrysenior.com'
baseurl: ''
title: 'Henry Senior'
description: 'Personal blog'
permalink: pretty
# logo: "https://avatars.githubusercontent.com/u/3028359?v=4"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Words
  url: /blog/

# Footer nav
navigation_footer:
- title: ğŸ‘¨â€ğŸ’»
  url: "https://github.com/Delphboy"
- title: ğŸ“
  url: "https://scholar.google.com/citations?user=tL5MtX0AAAAJ&hl=en"
- title: ğŸ“· by James Sloane
  url: "http://jamessloane.com"

# Collections
collections:
  posts:
    title: Blog Posts
    output: true
    #description: "My thoughts and ideas"
    #feature_image: "https://images.unsplash.com/photo-1626963524641-8c45a4b7ad38?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=962&q=80"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages